#!/usr/bin/env bash
set -Eeuo pipefail

SERVICE_NAME="${SERVICE_NAME:-wechat-trilium}"
APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
ENV_FILE="$APP_DIR/.env"
ENV_EXAMPLE="$APP_DIR/.env.example"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
NONINTERACTIVE="${INSTALL_NONINTERACTIVE:-0}"
USE_EXISTING_ENV="${INSTALL_USE_EXISTING_ENV:-0}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'EOF_HELP'
Usage:
  ./install.sh
  ./install.sh --use-existing-env

Environment overrides:
  SERVICE_NAME=wechat-trilium APP_DIR=/path/to/wechat ./install.sh
  INSTALL_NONINTERACTIVE=1 TRILIUM_ETAPI_TOKEN=xxx ./install.sh
  INSTALL_USE_EXISTING_ENV=1 ./install.sh

The script installs Python dependencies, writes .env, creates a systemd service,
enables it and starts it.
EOF_HELP
  exit 0
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --use-existing-env|--no-config)
      USE_EXISTING_ENV=1
      shift
      ;;
    --non-interactive)
      NONINTERACTIVE=1
      shift
      ;;
    *)
      printf '\033[1;31m[error]\033[0m unknown argument: %s\n' "$1" >&2
      exit 1
      ;;
  esac
done

if [[ "$(id -u)" -eq 0 ]]; then
  SUDO=""
  RUN_USER="${RUN_USER:-${SUDO_USER:-root}}"
else
  SUDO="sudo"
  RUN_USER="${RUN_USER:-$(id -un)}"
fi
RUN_GROUP="${RUN_GROUP:-$(id -gn "$RUN_USER" 2>/dev/null || id -gn)}"

log() { printf '\033[1;32m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "缺少命令：$1"; exit 1; }
}

run_as_root() {
  if [[ -n "$SUDO" ]]; then
    need_cmd sudo
    sudo "$@"
  else
    "$@"
  fi
}

get_env_value() {
  local key="$1" file="${2:-$ENV_FILE}"
  [[ -f "$file" ]] || return 0
  grep -E "^${key}=" "$file" | tail -n 1 | sed "s/^${key}=//" || true
}

random_token() {
  python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
}

prompt_value() {
  local key="$1" label="$2" default_value="$3" secret="${4:-0}"
  local current="${!key:-}"
  if [[ -z "$current" ]]; then
    current="$(get_env_value "$key")"
  fi
  if [[ -z "$current" ]]; then
    current="$default_value"
  fi

  if [[ "$NONINTERACTIVE" == "1" ]]; then
    printf '%s' "$current"
    return
  fi

  local input=""
  if [[ "$secret" == "1" ]]; then
    if [[ -n "$current" && "$current" != put-your-* && "$current" != change-me-* ]]; then
      read -r -s -p "$label [已设置，回车保持不变]: " input || true
    else
      read -r -s -p "$label [回车留空]: " input || true
    fi
    printf '\n' >&2
  else
    read -r -p "$label [$current]: " input || true
  fi

  if [[ -n "$input" ]]; then
    printf '%s' "$input"
  else
    printf '%s' "$current"
  fi
}

write_env() {
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp" <<EOF_ENV
# Generated by install.sh at $(date -u +'%Y-%m-%d %H:%M:%S UTC')
# 微信公众号服务器配置里你自己填写的 Token，不是 AppSecret
WECHAT_TOKEN=$WECHAT_TOKEN

# 下载图片/语音临时素材需要 AppID/AppSecret
WECHAT_APP_ID=$WECHAT_APP_ID
WECHAT_APP_SECRET=$WECHAT_APP_SECRET

# 公众号后台如选择兼容/安全模式，需要填写 43 位 EncodingAESKey；明文模式可留空
WECHAT_AES_KEY=$WECHAT_AES_KEY

# TriliumNext
TRILIUM_BASE_URL=$TRILIUM_BASE_URL
TRILIUM_ETAPI_TOKEN=$TRILIUM_ETAPI_TOKEN
TRILIUM_PARENT_NOTE_ID=$TRILIUM_PARENT_NOTE_ID

# gunicorn/systemd 监听配置。反代建议 127.0.0.1；直接公网访问用 0.0.0.0
BIND_HOST=$BIND_HOST
HOST=0.0.0.0
PORT=$PORT
GUNICORN_WORKERS=1
GUNICORN_THREADS=4
SAVE_WORKERS=2

# 按这个时区归档到日期文件夹
ARCHIVE_TIMEZONE=$ARCHIVE_TIMEZONE

# 只处理你自己的 OpenID；多个用英文逗号分隔
OWNER_OPENIDS=$OWNER_OPENIDS
PROCESS_OWNER_ONLY=$PROCESS_OWNER_ONLY

# 是否给自己回复“已保存”
REPLY_TO_OWNER=$REPLY_TO_OWNER
EOF_ENV

  if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
    warn "已备份原 .env"
  fi
  install -m 600 "$tmp" "$ENV_FILE"
  rm -f "$tmp"
  chown "$RUN_USER:$RUN_GROUP" "$ENV_FILE" 2>/dev/null || true
}

load_existing_env() {
  [[ -f "$ENV_FILE" ]] || { err "未找到 $ENV_FILE。请先 cp .env.example .env 并填写，或不带 --use-existing-env 运行脚本。"; exit 1; }

  WECHAT_TOKEN="$(get_env_value WECHAT_TOKEN)"
  WECHAT_APP_ID="$(get_env_value WECHAT_APP_ID)"
  WECHAT_APP_SECRET="$(get_env_value WECHAT_APP_SECRET)"
  WECHAT_AES_KEY="$(get_env_value WECHAT_AES_KEY)"
  TRILIUM_BASE_URL="$(get_env_value TRILIUM_BASE_URL)"
  TRILIUM_ETAPI_TOKEN="$(get_env_value TRILIUM_ETAPI_TOKEN)"
  TRILIUM_PARENT_NOTE_ID="$(get_env_value TRILIUM_PARENT_NOTE_ID)"
  BIND_HOST="$(get_env_value BIND_HOST)"
  PORT="$(get_env_value PORT)"
  ARCHIVE_TIMEZONE="$(get_env_value ARCHIVE_TIMEZONE)"
  OWNER_OPENIDS="$(get_env_value OWNER_OPENIDS)"
  PROCESS_OWNER_ONLY="$(get_env_value PROCESS_OWNER_ONLY)"
  REPLY_TO_OWNER="$(get_env_value REPLY_TO_OWNER)"

  BIND_HOST="${BIND_HOST:-127.0.0.1}"
  PORT="${PORT:-8000}"
  ARCHIVE_TIMEZONE="${ARCHIVE_TIMEZONE:-Asia/Shanghai}"
  PROCESS_OWNER_ONLY="${PROCESS_OWNER_ONLY:-true}"
  REPLY_TO_OWNER="${REPLY_TO_OWNER:-false}"
}

validate_config() {
  if [[ -z "${WECHAT_TOKEN:-}" || "${WECHAT_TOKEN:-}" == change-me-* ]]; then
    err "WECHAT_TOKEN 不能为空或默认值"
    exit 1
  fi
  if [[ -z "${TRILIUM_BASE_URL:-}" ]]; then
    err "TRILIUM_BASE_URL 不能为空"
    exit 1
  fi
  if [[ -z "${TRILIUM_ETAPI_TOKEN:-}" || "${TRILIUM_ETAPI_TOKEN:-}" == put-your-* ]]; then
    err "TRILIUM_ETAPI_TOKEN 不能为空或默认值"
    exit 1
  fi
  if [[ -z "${TRILIUM_PARENT_NOTE_ID:-}" ]]; then
    err "TRILIUM_PARENT_NOTE_ID 不能为空"
    exit 1
  fi
}

install_system_packages() {
  if command -v apt-get >/dev/null 2>&1; then
    log "安装系统依赖：python3 python3-venv python3-pip curl"
    run_as_root apt-get update
    run_as_root apt-get install -y python3 python3-venv python3-pip curl
  elif command -v dnf >/dev/null 2>&1; then
    log "安装系统依赖：python3 python3-pip curl"
    run_as_root dnf install -y python3 python3-pip curl
  elif command -v yum >/dev/null 2>&1; then
    log "安装系统依赖：python3 python3-pip curl"
    run_as_root yum install -y python3 python3-pip curl
  else
    warn "未识别包管理器，跳过系统依赖安装；请确认 python3/venv/pip 已安装"
  fi
}

create_venv() {
  need_cmd python3
  log "创建/更新 Python 虚拟环境"
  python3 -m venv "$APP_DIR/.venv"
  "$APP_DIR/.venv/bin/python" -m pip install --upgrade pip
  "$APP_DIR/.venv/bin/pip" install -r "$APP_DIR/requirements.txt"
  "$APP_DIR/.venv/bin/python" -m py_compile "$APP_DIR/app.py"
}

install_service() {
  log "写入 systemd 服务：$SERVICE_FILE"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp" <<EOF_SERVICE
[Unit]
Description=WeChat to TriliumNext bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
Group=$RUN_GROUP
WorkingDirectory=$APP_DIR
Environment=APP_DIR=$APP_DIR
EnvironmentFile=$ENV_FILE
ExecStart=/bin/bash -lc 'exec "\$APP_DIR/.venv/bin/gunicorn" --workers "\${GUNICORN_WORKERS:-1}" --threads "\${GUNICORN_THREADS:-4}" --bind "\${BIND_HOST:-127.0.0.1}:\${PORT:-8000}" --access-logfile - --error-logfile - --capture-output --log-level info app:app'
Restart=always
RestartSec=5
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF_SERVICE
  run_as_root install -m 644 "$tmp" "$SERVICE_FILE"
  rm -f "$tmp"
  run_as_root systemctl daemon-reload
  run_as_root systemctl enable --now "$SERVICE_NAME"
}

print_summary() {
  echo
  log "安装完成"
  echo "服务名：$SERVICE_NAME"
  echo "项目目录：$APP_DIR"
  echo "监听地址：$BIND_HOST:$PORT"
  echo
  echo "查看状态："
  echo "  sudo systemctl status $SERVICE_NAME --no-pager"
  echo "查看日志："
  echo "  sudo journalctl -u $SERVICE_NAME -f"
  echo "重启服务："
  echo "  sudo systemctl restart $SERVICE_NAME"
  echo
  if command -v curl >/dev/null 2>&1; then
    local ip
    ip="$(curl -4 -fsS --max-time 5 https://ifconfig.me 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then
      echo "当前服务器公网出口 IPv4：$ip"
      echo "如果要保存语音/临时素材，请把这个 IP 加到公众号后台 IP 白名单。"
    fi
  fi
  echo
  if [[ "$BIND_HOST" == "127.0.0.1" ]]; then
    echo "公众号回调 URL 应通过 Nginx/隧道反代到 http://127.0.0.1:$PORT/wechat"
  else
    echo "公众号回调 URL 可以是：http://你的服务器IP:$PORT/wechat"
  fi
}

main() {
  cd "$APP_DIR"
  [[ -f "$APP_DIR/app.py" ]] || { err "未找到 $APP_DIR/app.py，请在项目目录中运行 install.sh"; exit 1; }
  [[ -f "$APP_DIR/requirements.txt" ]] || { err "未找到 $APP_DIR/requirements.txt"; exit 1; }

  install_system_packages

  if [[ "$USE_EXISTING_ENV" == "1" ]]; then
    log "使用已有 .env，不进行交互配置，也不会覆盖 .env"
    load_existing_env
  else
    local default_token
    default_token="$(get_env_value WECHAT_TOKEN)"
    [[ -n "$default_token" && "$default_token" != change-me-* ]] || default_token="$(random_token)"

    echo
    log "填写配置。已有 .env 时，直接回车会保留原值。"
    WECHAT_TOKEN="$(prompt_value WECHAT_TOKEN '微信服务器 Token' "$default_token" 1)"
    WECHAT_APP_ID="$(prompt_value WECHAT_APP_ID '微信公众号 AppID' 'wx2e25b1880ef70eba')"
    WECHAT_APP_SECRET="$(prompt_value WECHAT_APP_SECRET '微信公众号 AppSecret（下载图片/语音需要）' '' 1)"
    WECHAT_AES_KEY="$(prompt_value WECHAT_AES_KEY 'EncodingAESKey（明文模式可留空）' '' 1)"
    TRILIUM_BASE_URL="$(prompt_value TRILIUM_BASE_URL 'TriliumNext 地址' 'https://trilium.azhen.de')"
    TRILIUM_ETAPI_TOKEN="$(prompt_value TRILIUM_ETAPI_TOKEN 'Trilium ETAPI Token' '' 1)"
    TRILIUM_PARENT_NOTE_ID="$(prompt_value TRILIUM_PARENT_NOTE_ID 'Trilium 父笔记 ID' 'PYAtaQPDBHKf')"
    BIND_HOST="$(prompt_value BIND_HOST '监听主机：反代用127.0.0.1，直接公网用0.0.0.0' '127.0.0.1')"
    PORT="$(prompt_value PORT '监听端口' '8000')"
    ARCHIVE_TIMEZONE="$(prompt_value ARCHIVE_TIMEZONE '归档时区' 'Asia/Shanghai')"
    OWNER_OPENIDS="$(prompt_value OWNER_OPENIDS '只处理这些 OpenID，多个用逗号分隔' 'o_Yjr0Uhm19Xb9kG24PqIBUEP_eE')"
    PROCESS_OWNER_ONLY="$(prompt_value PROCESS_OWNER_ONLY '是否只处理上述 OpenID true/false' 'true')"
    REPLY_TO_OWNER="$(prompt_value REPLY_TO_OWNER '是否回复“已保存” true/false' 'false')"

    validate_config
    write_env
  fi

  validate_config
  create_venv
  install_service
  print_summary
}

main "$@"
